[project]
name = "pyEDITH"
version = "1.7.0"
authors = [
  { name = "Eleonora Alei", email = "eleonora.alei@nasa.gov" },
  { name = "Miles Currie", email = "miles.h.currie@nasa.gov" },
   { name = "Corey Spohn", email = "corey.a.spohn@nasa.gov" },
]
description = "Exposure Direct Imaging Timer for HWO (Python Version)"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "numpy",
  "scipy",
  "astropy",
  "pandas",
  "yippy>=2.7.3",
  "openpyxl",
  "synphot",
  "eacy",
  "hwostyle",
]

# Optional dependencies for testing
[project.optional-dependencies]
test = ["pytest", "pytest-cov", "pooch"]

[project.urls]
Homepage = "https://github.com/HabitableWorldsObservatory/pyEDITH/"
Issues = "https://github.com/HabitableWorldsObservatory/pyEDITH/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["pyEDITH", "pyEDITH.components"]
include-package-data = true


[project.scripts]
pyedith = "pyEDITH.cli:main"
