name: Run tests and upload coverage

on: 
  [push,pull_request]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov numpy astropy scipy pandas yippy openpyxl synphot eacy
          pip install .
          

      - name: Clone required repository
        run: |
            git clone https://github.com/HWO-GOMAP-Working-Groups/Sci-Eng-Interface sci-eng-repo
            echo "SCI_ENG_DIR=${{ github.workspace }}/sci-eng-repo/hwo_sci_eng" >> $GITHUB_ENV
            
      - name: Run tests
        run:  pytest tests/ --cov=src/pyEDITH --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


